parameters:
- name: Subscription
  type: string
  default: $(Subscription)

- name: ClusterName
  type: string
  default: $(GameName)

- name: RGName
  type: string
  default: $(GameName)-rg

- name: WorkingDir
  type: string
  default: $(System.DefaultWorkingDirectory)/charts

steps:
- task: AzureCLI@2
  displayName: Install Nginx
  inputs:
    azureSubscription: ${{ parameters.Subscription }}
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      Write-Host "Get KubeConfig"
      az aks get-credentials --name ${{ parameters.ClusterName }} --resource-group ${{ parameters.RGName }}

      Write-Host "Go to WorkingDir"
      cd ${{ parameters.WorkingDir }}

      Write-Host "Install Traefik"
      helm upgrade traefik ./traefik/traefik/ -f ./traefik-values.yaml --namespace traefik --create-namespace -i
