apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  labels:
    app: login
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
        {{ include "mmorpg.labels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: loginservice
        imagePullPolicy: IfNotPresent
        image: loginservice:latest
        ports:
        - name: login
          containerPort: 3333
