parameters:
- name: ExecuteTerraform
  type: boolean
  default: true

trigger: none

variables:
- group: kdsmmorpg

stages:
- stage: Infrastructure
  displayName: Infrastructure
  dependsOn: []
  jobs:
  - job: Infrastructure
    displayName: Infrastructure
    pool: 
      vmImage: ubuntu-latest
    workspace:
        clean: all
    steps:
    - template: steps/terraformExecute.yaml
      parameters:
        ExecuteTerraform: ${{ parameters.ExecuteTerraform }}

- stage: GameBuild
  displayName: GameBuild
  dependsOn:
  - Infrastructure
  jobs:
  - job: GameBuild
    displayName: GameBuild
    pool: 
      vmImage: ubuntu-latest
    workspace:
        clean: all
    steps:
    - template: steps/gamebuild.yaml

- stage: GameDeploy
  displayName: GameDeploy
  dependsOn:
  - GameBuild
  jobs:
  - job: GameDeploy
    displayName: GameDeploy
    pool: 
      vmImage: ubuntu-latest
    workspace:
        clean: all
    steps:
    - template: steps/gamedeploy.yaml

- stage: Monitoring
  displayName: Monitoring
  dependsOn:
  - Infrastructure
  jobs:
  - job: Monitoring
    displayName: Monitoring
    pool: 
      vmImage: ubuntu-latest
    workspace:
        clean: all
    steps:
    - template: steps/monitoring.yaml
