parameters:
- name: ExecuteTerraform
  type: boolean
  default: true

trigger: none

variables:
- group: kdsmmorpg

stages:
- stage: Infrastructure
  displayName: Infrastructure
  dependsOn: []
  jobs:
  - job: Infrastructure
    displayName: Infrastructure
    pool: 
      vmImage: ubuntu-latest
    workspace:
        clean: all
    steps:
    - template: steps/terraformExecute.yaml
      parameters:
        ExecuteTerraform: ${{ parameters.ExecuteTerraform }}

- stage: LoginService
  displayName: LoginService
  dependsOn:
  - Infrastructure
  jobs:
  - job: LoginService
    displayName: LoginService
    pool: 
      vmImage: ubuntu-latest
    workspace:
        clean: all
    steps:
    - template: steps/servicebuild.yaml
      parameters:
        ServicePath: LoginService
        RepositoryName: loginservice
        
- stage: WorldChatService
  displayName: WorldChatService
  dependsOn:
  - Infrastructure
  jobs:
  - job: WorldChatService
    displayName: WorldChatService
    pool: 
      vmImage: ubuntu-latest
    workspace:
        clean: all
    steps:
    - template: steps/servicebuild.yaml
      parameters:
        ServicePath: WorldChatService
        RepositoryName: worldchatservice
        
- stage: CharacterService
  displayName: CharacterService
  dependsOn:
  - Infrastructure
  jobs:
  - job: CharacterService
    displayName: CharacterService
    pool: 
      vmImage: ubuntu-latest
    workspace:
        clean: all
    steps:
    - template: steps/servicebuild.yaml
      parameters:
        ServicePath: CharacterService
        RepositoryName: characterservice

- stage: MapService
  displayName: MapService
  dependsOn:
  - Infrastructure
  jobs:
  - job: MapService
    displayName: MapService
    pool: 
      vmImage: ubuntu-latest
    workspace:
        clean: all
    steps:
    - template: steps/servicebuild.yaml
      parameters:
        ServicePath: MapService
        RepositoryName: mapservice

- stage: Monitoring
  displayName: Monitoring
  dependsOn:
  - Infrastructure
  jobs:
  - job: Monitoring
    displayName: Monitoring
    pool: 
      vmImage: ubuntu-latest
    workspace:
        clean: all
    steps:
    - template: steps/monitoring.yaml

- stage: Traefik
  displayName: Traefik
  dependsOn:
  - Infrastructure
  jobs:
  - job: Traefik
    displayName: Traefik
    pool: 
      vmImage: ubuntu-latest
    workspace:
        clean: all
    steps:
    - template: steps/traefik.yaml

- stage: GameDeploy
  displayName: GameDeploy
  dependsOn:
  - LoginService
  - CharacterService
  - WorldChatService
  - MapService
  - Traefik
  jobs:
  - job: GameDeploy
    displayName: GameDeploy
    pool: 
      vmImage: ubuntu-latest
    workspace:
        clean: all
    steps:
    - template: steps/gamedeploy.yaml
