apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  labels:
    app: login
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: loginservice
        imagePullPolicy: IfNotPresent
        image: loginservice:latest
        ports:
        - name: login
          containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: login-svc
  labels:
    app: login
spec:
  type: NodePort
  selector:
    app: login
# issue with docker for windows https://github.com/docker/for-win/issues/9028
# in azure we need this
#  sessionAffinity: ClientIP
  ports:
  - name: login
    protocol: UDP
    port: 30000
    targetPort: 3334
    nodePort: 30000
