apiVersion: apps/v1
kind: Deployment
metadata:
  name: worldchat
  labels:
    app: worldchat
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: worldchat
  template:
    metadata:
      labels:
        app: worldchat
    spec:
      containers:
      - name: worldchatservice
        imagePullPolicy: IfNotPresent
        image: worldchatservice:latest
        ports:
        - name: worldchat
          containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: worldchat-svc
  labels:
    app: worldchat
spec:
  type: NodePort
  selector:
    app: worldchat
# issue with docker for windows https://github.com/docker/for-win/issues/9028
# in azure we need this
#  sessionAffinity: ClientIP
  ports:
  - name: worldchat
    protocol: UDP
    port: 3333
    targetPort: 3333
    nodePort: 30000
