apiVersion: apps/v1
kind: Deployment
metadata:
  name: worldchat2
  labels:
    app: worldchat2
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: worldchat2
  template:
    metadata:
      labels:
        app: worldchat2
    spec:
      containers:
      - name: worldchatservice
        imagePullPolicy: IfNotPresent
        image: worldchatservice:latest
        ports:
        - name: worldchat2
          containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: worldchat2-svc
  labels:
    app: worldchat2
spec:
  type: NodePort
  selector:
    app: worldchat2
# issue with docker for windows https://github.com/docker/for-win/issues/9028
# in azure we need this
#  sessionAffinity: ClientIP
  ports:
  - name: worldchat2
    protocol: UDP
    port: 30003
    targetPort: 3333
    nodePort: 30003
