imagePullSecrets:
  - name: acr-secret

characterPort: 30001
worldChatPort: 30002
mapTownPort: 31000
mapFieldPort: 31001
loginPort: 30000

cosmosUrl: "@@{CosmosUrl}@@"
cosmosKey: "@@{CosmosKey}@@"

loginServiceImage: "@@{GameName}@@acr.azurecr.io/loginservice:latest"
characterServiceImage: "@@{GameName}@@acr.azurecr.io/characterservice:latest"
worldChatServiceImage: "@@{GameName}@@acr.azurecr.io/worldchatservice:latest"
mapServiceImage: "@@{GameName}@@acr.azurecr.io/mapservice:latest"
