imagePullSecrets:
  - name: acr-secret

worldChatPort: 3333
loginPort: 3334
characterPort: 3335
mapTownPort: 3336
mapFieldPort: 3337
playerEventPort: 3338

cosmosUrl: "@@{CosmosUrl}@@"
cosmosKey: "@@{CosmosKey}@@"

loginServiceImage: "@@{GameName}@@acr.azurecr.io/loginservice:@@{Build.BuildNumber}@@"
characterServiceImage: "@@{GameName}@@acr.azurecr.io/characterservice:@@{Build.BuildNumber}@@"
worldChatServiceImage: "@@{GameName}@@acr.azurecr.io/worldchatservice:@@{Build.BuildNumber}@@"
mapServiceImage: "@@{GameName}@@acr.azurecr.io/mapservice:@@{Build.BuildNumber}@@"
dailyLoginServiceImage: "@@{GameName}@@acr.azurecr.io/dailyloginservice:@@{Build.BuildNumber}@@"
inventoryEventProcessorServiceImage: "@@{GameName}@@acr.azurecr.io/inventoryeventprocessorservice:@@{Build.BuildNumber}@@"
playerEventProcessorServiceImage: "@@{GameName}@@acr.azurecr.io/playereventprocessorservice:@@{Build.BuildNumber}@@"
playerEventServiceImage: "@@{GameName}@@acr.azurecr.io/playereventservice:@@{Build.BuildNumber}@@"

serviceType: ClusterIP

jwtSecret: "@@{JwtSecret}@@"
