imagePullSecrets:
  - name: acr-secret

characterPort: 3335
worldChatPort: 3333
mapTownPort: 3336
mapFieldPort: 3337
loginPort: 3334

cosmosUrl: "@@{CosmosUrl}@@"
cosmosKey: "@@{CosmosKey}@@"

loginServiceImage: "@@{GameName}@@acr.azurecr.io/loginservice:@@{Build.BuildNumber}@@"
characterServiceImage: "@@{GameName}@@acr.azurecr.io/characterservice:@@{Build.BuildNumber}@@"
worldChatServiceImage: "@@{GameName}@@acr.azurecr.io/worldchatservice:@@{Build.BuildNumber}@@"
mapServiceImage: "@@{GameName}@@acr.azurecr.io/mapservice:@@{Build.BuildNumber}@@"

serviceType: ClusterIP
characterDNS: "@@{GameName}@@char"
loginDNS: "@@{GameName}@@account"
mapFieldDNS: "@@{GameName}@@mapfield"
mapTownDNS: "@@{GameName}@@maptown"
worldChatDNS: "@@{GameName}@@worldchat"