imagePullSecrets:
  - name: acr-secret

worldChatPort: 3333
loginPort: 3334
characterPort: 3335
mapTownPort: 3336
mapFieldPort: 3337
playerEventPort: 3338
inventoryPort: 3339
combatTownPort: 3340
combaFieldPort: 3341
questPort: 3342

cosmos:
  emulator:
    deploy: false
  url: "@@{CosmosUrl}@@"
  key: "@@{CosmosKey}@@"

loginServiceImage: "@@{GameName}@@acr.azurecr.io/loginservice:@@{Build.BuildNumber}@@"
characterServiceImage: "@@{GameName}@@acr.azurecr.io/characterservice:@@{Build.BuildNumber}@@"
worldChatServiceImage: "@@{GameName}@@acr.azurecr.io/worldchatservice:@@{Build.BuildNumber}@@"
mapServiceImage: "@@{GameName}@@acr.azurecr.io/mapservice:@@{Build.BuildNumber}@@"
dailyLoginServiceImage: "@@{GameName}@@acr.azurecr.io/dailyloginservice:@@{Build.BuildNumber}@@"
inventoryEventProcessorServiceImage: "@@{GameName}@@acr.azurecr.io/inventoryeventprocessorservice:@@{Build.BuildNumber}@@"
playerEventProcessorServiceImage: "@@{GameName}@@acr.azurecr.io/playereventprocessorservice:@@{Build.BuildNumber}@@"
playerEventServiceImage: "@@{GameName}@@acr.azurecr.io/playereventservice:@@{Build.BuildNumber}@@"
inventoryServiceImage: "@@{GameName}@@acr.azurecr.io/inventoryservice:@@{Build.BuildNumber}@@"
enemyLoadBalancerServiceImage: "@@{GameName}@@acr.azurecr.io/enemyloadbalancerservice:@@{Build.BuildNumber}@@"
enemyWorkerServiceImage: "@@{GameName}@@acr.azurecr.io/enemyworkerservice:@@{Build.BuildNumber}@@"
combatServiceImage: "@@{GameName}@@acr.azurecr.io/combatservice:@@{Build.BuildNumber}@@"
questServiceImage: "@@{GameName}@@acr.azurecr.io/questservice:@@{Build.BuildNumber}@@"

mmorpg:
  deploy: false

serviceType: ClusterIP
redis:
  deploy: false
  url: redis-svc

jwtSecret: "@@{JwtSecret}@@"