apiVersion: v1
kind: Service
metadata:
  name: character-svc
  labels:
    app: character
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: character
    {{ include "mmorpg.selectorLabels" . | nindent 4 }}
# issue with docker for windows https://github.com/docker/for-win/issues/9028
# in azure we need this
#  sessionAffinity: ClientIP
  ports:
  - name: character
    protocol: UDP
    port: {{ .Values.characterPort }}
    targetPort: 3335
    nodePort: {{ .Values.characterPort }}
