apiVersion: v1
kind: Service
metadata:
  name: combattown-svc
  labels:
    app: combattown
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: combattown
    {{ include "mmorpg.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  ports:
  - name: combattown
    protocol: UDP
    port: 3339
    targetPort: 3339
    {{- if eq .Values.serviceType "NodePort" }}
    nodePort: {{ .Values.combatTownPort }}
    {{- end }}
