{{ if .Values.mmorpg.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: combattown
  labels:
    app: combattown
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combattown
  template:
    metadata:
      labels:
        app: combattown
        {{ include "mmorpg.labels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: combattownservice
        imagePullPolicy: IfNotPresent
        image: {{ .Values.combatServiceImage }}
        ports:
        - name: combattown
          containerPort: 3339
        env:
        - name: MAPNAME
          value: town
        - name: CosmosUrl
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosUrl
        - name: CosmosKey
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosKey
        - name: JwtSecret
          value: {{ .Values.jwtSecret }}
        - name: REDIS
          value: {{ .Values.redis.url }}
{{ end }}