apiVersion: apps/v1
kind: Deployment
metadata:
  name: combatfield
  labels:
    app: combatfield
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: combatfield
  template:
    metadata:
      labels:
        app: combatfield
        {{ include "mmorpg.labels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: combatfieldservice
        imagePullPolicy: Always
        image: {{ .Values.combatServiceImage }}
        ports:
        - name: combatfield
          containerPort: 3339
        env:
        - name: CosmosUrl
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosUrl
        - name: CosmosKey
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosKey
        - name: JwtSecret
          value: {{ .Values.jwtSecret }}
