apiVersion: v1
kind: Service
metadata:
  name: combatfield-svc
  labels:
    app: combatfield
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: combatfield
    {{ include "mmorpg.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  ports:
  - name: combatfield
    protocol: UDP
    port: {{ .Values.combatfieldPort }}
    targetPort: 3339
    {{- if eq .Values.serviceType "NodePort" }}
    nodePort: {{ .Values.combatfieldPort }}
    {{- end }}
