apiVersion: v1
kind: Secret
metadata:
  name: cosmossecret
  annotations:
    kubernetes.io/service-account.name: "sa-name"
type: Opaque
stringData:
  CosmosUrl: {{ .Values.cosmos.url }}
  CosmosKey: {{ .Values.cosmos.key }}
