apiVersion: v1
kind: Secret
metadata:
  name: CosmosSecret
  annotations:
    kubernetes.io/service-account.name: "sa-name"
type: Opaque
stringData:
  CosmosUrl: {{ .Values.cosmosUrl }}
  CosmosKey: {{ .Values.cosmosKey }}
