apiVersion: apps/v1
kind: Deployment
metadata:
  name: enemyworkerfield
  labels:
    app: enemyworkerfield
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enemyworkerfield
  template:
    metadata:
      labels:
        app: enemyworkerfield
        {{ include "mmorpg.labels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: enemyworkerfield
        imagePullPolicy: IfNotPresent
        image: {{ .Values.enemyWorkerServiceImage }}
        env:
        - name: MAPNAME
          value: field
        - name: CosmosUrl
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosUrl
        - name: CosmosKey
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosKey
        - name: REDIS
          value: {{ .Values.redis.url }}
