apiVersion: apps/v1
kind: Deployment
metadata:
  name: inveventproc
  labels:
    app: inveventproc
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inveventproc
  template:
    metadata:
      labels:
        app: inveventproc
        {{ include "mmorpg.labels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: inventoryeventprocessorservice
        imagePullPolicy: IfNotPresent
        image: {{ .Values.inventoryEventProcessorServiceImage }}
        env:
        - name: CosmosUrl
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosUrl
        - name: CosmosKey
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosKey

