{{ if .Values.mmorpg.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: inventory-svc
  labels:
    app: inventory
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: inventory
    {{ include "mmorpg.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  ports:
  - name: inventory
    protocol: UDP
    port: 3338
    targetPort: 3338
    {{- if eq .Values.serviceType "NodePort" }}
    nodePort: {{ .Values.inventoryPort }}
    {{- end }}
{{ end }}