apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  labels:
    app: login
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
        {{ include "mmorpg.labels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: loginservice
        imagePullPolicy: Always
        image: {{ .Values.loginServiceImage }}
        ports:
        - name: login
          containerPort: 3333
        env:
        - name: CosmosUrl
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosUrl
        - name: CosmosKey
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosKey
