apiVersion: v1
kind: Service
metadata:
  name: login-svc
  {{- if eq .Values.serviceType "LoadBalancer" }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.loginDNS }}
  {{- end }}
  labels:
    app: login
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: login
    {{ include "mmorpg.selectorLabels" . | nindent 4}}
  sessionAffinity: ClientIP
  ports:
  - name: login
    protocol: UDP
    port: {{ .Values.loginPort }}
    targetPort: 3334
    {{- if eq .Values.serviceType "NodePort" }}
    nodePort: {{ .Values.loginPort }}
    {{- end }}
