apiVersion: v1
kind: Service
metadata:
  name: login-svc
  labels:
    app: login
spec:
  type: NodePort
  selector:
    app: login
    {{ include "mmorpg.selectorLabels" . | nindent 4}}
# issue with docker for windows https://github.com/docker/for-win/issues/9028
# in azure we need this
#  sessionAffinity: ClientIP
  ports:
  - name: login
    protocol: UDP
    port: {{ .Values.loginPort }}
    targetPort: 3334
    nodePort: {{ .Values.loginPort }}
