apiVersion: v1
kind: Service
metadata:
  name: login-svc
  labels:
    app: login
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: login
    {{ include "mmorpg.selectorLabels" . | nindent 4}}
  sessionAffinity: ClientIP
  ports:
  - name: login
    protocol: UDP
    port: 3334
    targetPort: 3334
    {{- if eq .Values.serviceType "NodePort" }}
    nodePort: {{ .Values.loginPort }}
    {{- end }}
