apiVersion: v1
kind: Service
metadata:
  name: mapfield-svc
  labels:
    app: mapfield
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: mapfield
    {{ include "mmorpg.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  ports:
  - name: mapfield
    protocol: UDP
    port: {{ .Values.mapFieldPort }}
    targetPort: 3336
    {{- if eq .Values.serviceType "NodePort" }}
    nodePort: {{ .Values.mapFieldPort }}
    {{- end }}
