apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapfield
  labels:
    app: mapfield
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mapfield
  template:
    metadata:
      labels:
        app: mapfield
        {{ include "mmorpg.labels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: mapservice
        imagePullPolicy: IfNotPresent
        image: mapservice:latest
        ports:
        - name: mapfield
          containerPort: 3333
        env:
        - name: MAPNAME
          value: Field
