apiVersion: apps/v1
kind: Deployment
metadata:
  name: maptown
  labels:
    app: maptown
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: maptown
  template:
    metadata:
      labels:
        app: maptown
        {{ include "mmorpg.labels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: mapservice
        imagePullPolicy: Always
        image: {{ .Values.mapServiceImage }}
        ports:
        - name: maptown
          containerPort: 3336
        env:
        - name: MAPNAME
          value: Town
        - name: CosmosUrl
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosUrl
        - name: CosmosKey
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosKey
