apiVersion: apps/v1
kind: Deployment
metadata:
  name: playerevent
  labels:
    app: playerevent
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playerevent
  template:
    metadata:
      labels:
        app: playerevent
        {{ include "mmorpg.labels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: playereventservice
        imagePullPolicy: IfNotPresent
        image: {{ .Values.playerEventServiceImage }}
        ports:
        - name: playerevent
          containerPort: 3337
        env:
        - name: CosmosUrl
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosUrl
        - name: CosmosKey
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosKey
        - name: JwtSecret
          value: {{ .Values.jwtSecret }}
        - name: REDIS
          value: {{ .Values.redis.url }}
