{{ if .Values.mmorpg.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: playerevent-svc
  labels:
    app: playerevent
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: playerevent
    {{ include "mmorpg.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  ports:
  - name: playerevent
    protocol: UDP
    port: 3337
    targetPort: 3337
    {{- if eq .Values.serviceType "NodePort" }}
    nodePort: {{ .Values.playerEventPort }}
    {{- end }}
{{ end }}