apiVersion: apps/v1
kind: Deployment
metadata:
  name: propmgrtown
  labels:
    app: propmgrtown
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: propmgrtown
  template:
    metadata:
      labels:
        app: propmgrtown
        {{ include "mmorpg.labels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: propmanagementservice
        imagePullPolicy: Always
        image: {{ .Values.propManagementServiceImage }}
        env:
        - name: MAPNAME
          value: Town
        - name: CosmosUrl
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosUrl
        - name: CosmosKey
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosKey

