{{ if .Values.mmorpg.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: quest-svc
  labels:
    app: quest
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: quest
    {{ include "mmorpg.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  ports:
  - name: quest
    protocol: UDP
    port: 3340
    targetPort: 3340
    {{- if eq .Values.serviceType "NodePort" }}
    nodePort: {{ .Values.questPort }}
    {{- end }}
{{ end }}