apiVersion: apps/v1
kind: Deployment
metadata:
  name: worldchat
  labels:
    app: worldchat
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: worldchat
  template:
    metadata:
      labels:
        app: worldchat
        {{ include "mmorpg.labels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: worldchatservice
        imagePullPolicy: Always
        image: {{ .Values.worldChatServiceImage }}
        ports:
        - name: worldchat
          containerPort: 3333
        env:
        - name: CosmosUrl
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosUrl
        - name: CosmosKey
          valueFrom:
            secretKeyRef:
              name: cosmossecret
              key: CosmosKey
