apiVersion: v1
kind: Service
metadata:
  name: worldchat-svc
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.worldChatDNS }}
  labels:
    app: worldchat
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: worldchat
    {{ include "mmorpg.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  ports:
  - name: worldchat
    protocol: UDP
    port: {{ .Values.worldChatPort }}
    targetPort: 3333
    {{- if eq .Values.serviceType "NodePort" }}
    nodePort: {{ .Values.worldChatPort }}
    {{- end }}
