apiVersion: v1
kind: Service
metadata:
  name: worldchat-svc
  labels:
    app: worldchat
    {{ include "mmorpg.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: worldchat
    {{ include "mmorpg.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  ports:
  - name: worldchat
    protocol: UDP
    port: {{ .Values.worldChatPort }}
    targetPort: 3333
    nodePort: {{ .Values.worldChatPort }}
